services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Comunicação entre os microserviços TCP
      - "15672:15672" # Interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
